language: node_js

#Elegimos las diferentes versiones de node donde queremos que se ejecuten los tests:
node_js:
  - "node" #La última versión estable
  - "lts/*" #La útlima versión LTS (Soporte a Largo Plazo)
  - "14.13.1" #La versión que utilizo localmente

#ANTES DE INSTALAR: actualizamos la versión de npm para que sea la misma que la nuestra
before_install:
  - npm update npm@6.14.8

#Después de before_install, automaticamente travis ejecuta el comando npm ci, por lo que se instalan las dependencias
#Ahora sólo falta ejecutar los tests, en este caso con grunt como gestor de tareas y jest como framework de tests:
script: grunt test