version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: 
        name: Construcci贸n de la imagen de la aplicaci贸n
        command: docker build -t antoniorev/listenyourmood .

     - run: 
        name: Ejecuci贸n de la imagen de la aplicaci贸n
        command: docker run -t -v `pwd`:/test antoniorev/listenyourmood