#Escogemos la versión de CircleCI, en este caso la 2.1 por ser la más actualizada y más completa
version: 2.1


jobs:
 build:
   docker: 
      #Indicamos la imagen de docker (ya buildeada) donde queremos que se ejecuten los comandos. La imagen se obtiene de DockerHub
      - image: antoniorev/listenyourmood:latest
      
   steps:
      #Checkout realiza una comprobación de los archivos de código
      - checkout
      - run:
         name: Install grunt
         command: sudo npm install -g grunt
      - run:
         name: Install grunt-run
         command: sudo npm install -g grunt-run 
      #Ejecutamos los test
      - run:  
         name: Ejecución de la imagen de la aplicación
         command: grunt test