version: 2.1
jobs:
 build:
   docker: antoniorev/listenyourmood:latest
   steps:
     - checkout
     - run: 
        name: Ejecución de la imagen de la aplicación
        command: docker run -t -v `pwd`:/test antoniorev/listenyourmood