version: 2.1
jobs:
 build:
   docker: 
      - image: antoniorev/listenyourmood:latest
   steps:
     - checkout
     - run: 
        name: Ejecución de la imagen de la aplicación
        command: npm run test